# Generated by Django 4.1.3 on 2022-11-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название станции')),
                ('condition', models.CharField(default='running', max_length=7, verbose_name='Состояние станции')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания станции')),
                ('date_crash', models.DateTimeField(blank=True, null=True)),
                ('x', models.IntegerField(default=100, verbose_name='Ось x')),
                ('y', models.IntegerField(default=100, verbose_name='Ось y')),
                ('z', models.IntegerField(default=100, verbose_name='Ось z')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(max_length=1, verbose_name='Ось координат')),
                ('distance', models.IntegerField(verbose_name='Дистанция')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_move', to='stations.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещение',
            },
        ),
    ]
